apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erpnext-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"

    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Frappe-Site-Name erpnext.local;
spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
