apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-long
spec:
  replicas: 1

  selector:
    matchLabels:
      app: queue-long

  template:
    metadata:
      labels:
        app: queue-long

    spec:
      containers:
        - name: queue-long
          image: shiva9828/frappe-queue-long:v16.33.0

          command:
            - bench
            - worker
            - --queue
            - long

          envFrom:
            - configMapRef:
                name: erpnext-config
            - secretRef:
                name: erpnext-secret