apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites-pvc
  namespace: erpnext
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
